language: haskell
before_install:
 - cabal install alex
 - cabal install happy
 - cabal install gtk2hs-buildtools
install: 
 - cd yi
 - cabal install -fpango --alex-options="--debug"
 - cd -
 - cd yi-contrib
 - cabal install
