language: haskell
before_install:
 - cabal install alex
 - cabal install happy
 - cabal install gtk2hs-buildtools
install: 
 - cd yi
 - cabal install -fpango --enable-tests -ftesting --only-dependencies
 - cabal configure -fpango --enable-tests -ftesting
 - cabal build
 - cabal test | grep -v '\[OK\]'
 - cabal install -fpango
 - cd -
 - cd yi-contrib
 - cabal install
